# Persistent Volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-testnet-relay
spec:
  capacity:
    storage: 150Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/disks/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2

# Persistent Volume Claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-claim-testnet-relay
  namespace: cardano-testnet
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  


# Relay Pod
---
apiVersion: v1
kind: Pod
metadata:
  name: relay
  namespace: cardano-testnet
  labels:
    app: cardano
    pod: relay
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node2
  containers:
  - name: relay
    image: registry.gitlab.com/jasonwbrown23/cardano/cardano-node:1.29.0-aarch64
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "3"
        memory: "6Gi"
      requests:
        cpu: "1"
        memory: "1Gi"
    livenessProbe: &probe d
      initialDelaySeconds: 10
      periodSeconds: 20
      exec:
        command:
        - /bin/bash
        - -c
        - curl -f --retry 6 --max-time 5 --retry-delay 10 --retry-max-time 60 "http://localhost:12798/metrics"
    readinessProbe: *probe   
    ports:
      - containerPort: 3001
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    command: ["cardano-node"]
    args: [ 
            "run",
            "--topology", "/etc/config/testnet-topology.json",
            "--database-path", "/db",
            "--socket-path", "/db/node.socket",
            "--host-addr",  "0.0.0.0",
            "--port", "3001",
            "--config", "/etc/config/testnet-config.json" 
          ]
    volumeMounts:
    - name: datavol
      mountPath: /db
  volumes:
  - name: datavol
    persistentVolumeClaim:
      claimName: local-pvc-claim-testnet-relay
